name: Android Debug APK + PWA
on:
  push:
    branches:
      - main
  workflow_dispatch:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Create tiny PWA bundle
        run: |
          set -e
          APP_NAME="${{ github.event.repository.name || 'LastApp' }}"
          mkdir -p pwa/icons
          BASE64_PNG="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO0vK9kAAAAASUVORK5CYII="
          printf '%s' "$BASE64_PNG" | base64 -d > pwa/icons/icon-192.png
          printf '%s' "$BASE64_PNG" | base64 -d > pwa/icons/icon-512.png

          cat > pwa/manifest.json <<JSON
          {
            "name": "${APP_NAME}",
            "short_name": "${APP_NAME}",
            "start_url": "./index.html",
            "display": "standalone",
            "background_color": "#ffffff",
            "theme_color": "#ffffff",
            "icons": [
              {"src": "./icons/icon-192.png","sizes": "192x192","type": "image/png"},
              {"src": "./icons/icon-512.png","sizes": "512x512","type": "image/png"}
            ]
          }
          JSON

          cat > pwa/sw.js <<'JS'
          self.addEventListener('install', e => { self.skipWaiting(); });
          self.addEventListener('activate', e => { self.clients.claim(); });
          self.addEventListener('fetch', e => {});
          JS

          cat > pwa/index.html <<'HTML'
          <!doctype html><html><head>
            <meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
            <link rel="manifest" href="./manifest.json">
            <title>Install App</title>
          </head><body>
            <h1>Install this app</h1>
            <p>On Android: tap menu → "Add to Home screen". On iOS Safari: Share → "Add to Home Screen".</p>
            <script>if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js');}</script>
          </body></html>
          HTML

      - name: Collect artifact payload
        run: |
          set -e
          mkdir -p artifact
          cp build/app/outputs/flutter-apk/app-debug.apk artifact/ || true
          cp -r pwa artifact/web

      - name: Upload artifact (apk + pwa)
        uses: actions/upload-artifact@v4
        with:
          name: lastapp-build
          path: artifact
